import HairdresserImage from '../assets/images/hairdresser.jpg';
import HairdresserImage2 from '../assets/images/hairdresser-2.jpg';

const initialState = {
    filters: {},
    product: {},
    productList: [
        {
            brand: 'ABC Haircut',
            category: 'Hair Cut',
            highestPrice: 15,
            image: HairdresserImage,
            isFavourited: true,
            lowestPrice: 15,
            rating: 0.51,
            numOfRatings: 10,
            id: '1',
        },
        {
            brand: 'ABC Haircut',
            category: 'Facial',
            highestPrice: 25,
            image: HairdresserImage,
            isFavourited: false,
            lowestPrice: 15,
            rating: 1.21,
            numOfRatings: 10,
            id: '1',
        },
        {
            brand: 'ABC Haircut',
            category: 'Massage',
            highestPrice: 115,
            image: HairdresserImage,
            isFavourited: true,
            lowestPrice: 5,
            rating: 1.51,
            numOfRatings: 10,
            id: '1',
        },
        {
            brand: 'ABC Haircut',
            category: 'Manicure',
            highestPrice: 115,
            image: HairdresserImage,
            isFavourited: true,
            lowestPrice: 15,
            rating: 2.91,
            numOfRatings: 10,
            id: '1',
        },
        {
            brand: 'ABC Haircut',
            category: 'Hair Treatment',
            highestPrice: 55,
            image: HairdresserImage,
            isFavourited: true,
            lowestPrice: 25,
            rating: 3.41,
            numOfRatings: 10,
            id: '1',
        },
        {
            brand: 'ABC Haircut',
            category: 'Hair Cut',
            highestPrice: 15,
            image: HairdresserImage2,
            isFavourited: true,
            lowestPrice: 15,
            rating: 3.99,
            numOfRatings: 10,
            id: '1',
        },
        {
            brand: 'ABC Haircut',
            category: 'Hair Treatment',
            highestPrice: 15,
            image: HairdresserImage2,
            isFavourited: true,
            lowestPrice: 15,
            rating: 4.01,
            numOfRatings: 10,
            id: '1',
        },
        {
            brand: 'ABC Haircut',
            category: 'Massage',
            highestPrice: 15,
            image: HairdresserImage2,
            isFavourited: true,
            lowestPrice: 15,
            rating: 4.49,
            numOfRatings: 10,
            id: '1',
        },
        {
            brand: 'ABC Haircut',
            category: 'Manicure',
            highestPrice: 25,
            image: HairdresserImage2,
            isFavourited: true,
            lowestPrice: 15,
            rating: 4.56,
            numOfRatings: 10,
            id: '1',
        },
        {
            brand: 'ABC Haircut',
            category: 'Massage',
            highestPrice: 15,
            image: HairdresserImage,
            isFavourited: true,
            lowestPrice: 15,
            rating: 2.01,
            numOfRatings: 10,
            id: '1',
        },
        {
            brand: 'ABC Haircut',
            category: 'Massage',
            highestPrice: 511,
            image: HairdresserImage,
            isFavourited: true,
            lowestPrice: 299,
            rating: 5,
            numOfRatings: 10,
            id: '1',
        },
    ],
    trendingList: [
        {
            brand: 'ABC Haircut',
            category: 'Haircut',
            image: HairdresserImage2,
            location: 'ABC Road',
            rating: 0.5,
            numOfRatings: 10,
            id: '1',
        },
        {
            brand: 'ABC Haircut',
            category: 'Haircut',
            image: HairdresserImage2,
            location: 'ABC Road',
            rating: 1.2,
            numOfRatings: 10,
            id: '1',
        },
        {
            brand: 'ABC Haircut',
            category: 'Haircut',
            image: HairdresserImage2,
            location: '6 Petir Rd',
            rating: 2.3,
            numOfRatings: 10,
            id: '1',
        },
        {
            brand: 'ABC Haircut',
            category: 'Haircut',
            image: HairdresserImage,
            location: 'ABC Road',
            rating: 3.55,
            numOfRatings: 10,
            id: '1',
        },
        {
            brand: 'ABC Haircut',
            category: 'Haircut',
            image: HairdresserImage,
            location: 'ABC Road',
            rating: 4.89,
            id: '1',
            numOfRatings: 10,
        },
        {
            brand: 'ABC Haircut',
            category: 'Haircut',
            image: HairdresserImage,
            rating: 5.0,
            numOfRatings: 10,
            id: '1',
        },
        {
            brand: 'ABC Haircut',
            category: 'Haircut',
            image: HairdresserImage2,
            location: 'ABC Road',
            rating: 4.23,
            numOfRatings: 10,
            id: '1',
        },
        {
            brand: 'ABC Haircut',
            category: 'Haircut',
            image: HairdresserImage2,
            location: '17 Cheong Chin Nam Rd',
            rating: 4.26,
            numOfRatings: 10,
            id: '1',
        },
        {
            brand: 'ABC Haircut',
            category: 'Haircut',
            image: HairdresserImage2,
            location: 'ABC Road',
            rating: 4.49,
            numOfRatings: 10,
            id: '1',
        },
    ],
};

const productsReducer = (state = initialState, action) => {
    switch (action.type) {
        default:
            return state;
    }
};

export default productsReducer;
